development:
  password: shptka_2305df32d299e6a03dc0ab779f3dd8d7
  theme_id: "129466106115"
  store: baseball-shop-world.myshopify.com
production:
  password: shptka_2305df32d299e6a03dc0ab779f3dd8d7
  theme_id: "129464893699"
  store: baseball-shop-world.myshopify.com
